version: '3.8'
services:
  app:
    build: .
    container_name: share-a-ride-backend
    env_file:
      - .env
    ports:
      - "4002:4002"
    depends_on:
      - db
      - redis
    command: ["node", "app.js"]

  db:
    image: postgres:15-alpine
    container_name: share-a-ride-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sharearide
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: share-a-ride-redis
    ports:
      - "6379:6379"

volumes:
  pgdata: 